import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { CustomScrollbar } from "./components/CustomScrollbar";
import { Loader } from "./components/Loader";
import { PageTransitionOverlay } from "./components/PageTransitionOverlay";
import { SmoothScroll } from "./components/SmoothScroll";
import { CookieBanner } from "./components/CookieBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // Open Graph image paths are relative, and a crawler cannot fetch a relative
  // URL — without this Next falls back to localhost and every shared link
  // previews a broken image.
  metadataBase: new URL("https://studio.behsse.com"),
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="flex min-h-dvh flex-col">
        <Script id="disable-scroll-restoration" strategy="beforeInteractive">
          {`
            if ('scrollRestoration' in history) {
              history.scrollRestoration = 'manual';
            }
            window.scrollTo(0, 0);
          `}
        </Script>
        <SmoothScroll />
        <Loader />
        <PageTransitionOverlay />
        <Navbar />
        <CustomScrollbar />
        <main className="flex flex-1 flex-col">{children}</main>
        <CookieBanner />
      </body>
    </html>
  );
}
